# Generated by Django 3.0.3 on 2020-02-19 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('Match_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Match_Date', models.CharField(max_length=15)),
                ('Venue_Name', models.CharField(max_length=60)),
                ('Toss_Decision', models.CharField(max_length=10)),
                ('Is_Superover', models.IntegerField()),
                ('Is_Result', models.IntegerField()),
                ('Is_DuckWorthLewis', models.IntegerField()),
                ('Win_Type', models.CharField(max_length=10)),
                ('Won_By', models.CharField(blank=True, max_length=6, null=True)),
                ('City_Name', models.CharField(max_length=50)),
                ('Host_Country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('Player_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Player_Name', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=15)),
                ('Batting_Hand', models.CharField(max_length=20)),
                ('Bowling_Skill', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=30)),
                ('Is_Umpire', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Team_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Team_Name', models.CharField(max_length=50)),
                ('Team_Short_Code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('Season_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Season_Year', models.IntegerField()),
                ('Man_of_the_Series_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='man_of_the_series_id', to='ipl.Player')),
                ('Orange_Cap_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orange_cap_id', to='ipl.Player')),
                ('Purple_Cap_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purple_cap_id', to='ipl.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_Keeper', models.IntegerField()),
                ('Is_Captain', models.IntegerField()),
                ('Match_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playermatch_Match_Id', to='ipl.Match')),
                ('Player_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playermatch_Player_Id', to='ipl.Player')),
                ('Team_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playermatch_Team_Id', to='ipl.Team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='First_Umpire_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='First_Umpire_Id', to='ipl.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='Man_Of_The_Match_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Man_Of_The_Match_Id', to='ipl.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='Match_Winner_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Match_Winner_Id', to='ipl.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='Opponent_Team_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Opponent_Team_Id', to='ipl.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='Season_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_Season_Id', to='ipl.Season'),
        ),
        migrations.AddField(
            model_name='match',
            name='Second_Umpire_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Second_Umpire_Id', to='ipl.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='Team_Name_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_Name_Id', to='ipl.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='Toss_Winner_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Toss_Winner_Id', to='ipl.Team'),
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Innings_Id', models.IntegerField()),
                ('Over_Id', models.IntegerField()),
                ('Ball_Id', models.IntegerField()),
                ('Striker_Batting_Position', models.IntegerField()),
                ('Batsman_Scored', models.IntegerField(blank=True, null=True)),
                ('Extra_Type', models.CharField(blank=True, max_length=15, null=True)),
                ('Extra_Runs', models.IntegerField(blank=True, null=True)),
                ('Dissimal_Type', models.CharField(blank=True, max_length=25, null=True)),
                ('Bowler_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bowler_Id', to='ipl.Player')),
                ('Fielder_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fielder_Id', to='ipl.Player')),
                ('Match_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ball_Match_Id', to='ipl.Match')),
                ('Non_Striker_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Non_Striker_Id', to='ipl.Player')),
                ('Player_dissimal_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Player_dissimal_Id', to='ipl.Player')),
                ('Striker_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Striker_Id', to='ipl.Player')),
                ('Team_Batting_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_Batting_Id', to='ipl.Team')),
                ('Team_Bowling_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_Bowling_Id', to='ipl.Team')),
            ],
        ),
    ]
